import {Given,When,Then,} from "@badeball/cypress-cucumber-preprocessor";
import {MainPage} from "../../pages/MainPage.js"

const mainpage = new MainPage()

Given("User is located in main page", () =>{
    cy.visit("https://telnyx.com")
})
When("User clicks on link in 'Powerfull product' section", () => {
    mainpage.MessagingAPI()
    cy.intercept('https://telnyx.com/products/sms-api')
    cy.wait(1000)
    mainpage.MainPageButton()
    mainpage.VideoAPI()
    cy.intercept('https://telnyx.com/products/video-api')
    cy.wait(1000)
    mainpage.MainPageButton()
    mainpage.Wireless()
    cy.intercept('https://telnyx.com/products/iot-sim-card')
    cy.wait(1000)
    mainpage.MainPageButton()
    mainpage.VoiceAPIlink()
    cy.intercept('https://telnyx.com/products/voice-api')
    cy.wait(1000)
    mainpage.MainPageButton()
    mainpage.ElasticSIPTrunking()
    cy.intercept('https://telnyx.com/products/sip-trunks')
    cy.wait(1000)
    mainpage.MainPageButton()
    mainpage.Storage()
    cy.intercept('https://telnyx.com/products/storage')
    mainpage.MainPageButton()
})
When("User clicks on any links in footer", () => {
    mainpage.CookiesSkip()
    mainpage.Footer()
    cy.wait(1000)
    mainpage.CallControll()
    cy.wait(1000)
    mainpage.ProgrammableSMS()
    cy.wait(1000)
    mainpage.WhatsAppAPI()
    cy.wait(1000)
    mainpage.SecureFaxing()
    cy.wait(1000)
    mainpage.WirelessCellularIoT()
    cy.wait(1000)
    mainpage.NumberLookup()
    cy.wait(1000)
    mainpage.GlobalNumbers()
    cy.wait(1000)
    mainpage.VerifyAPI()
    cy.wait(1000)
    mainpage.SeeAllProducts()
    cy.wait(2000)
    mainpage.Blog()
    cy.wait(1000)
    mainpage.ResourceHub()
    cy.wait(1000)
    mainpage.ReleaseNotes()
    cy.wait(1000)
    mainpage.SMSAPI()
    cy.wait(1000)
    mainpage.VoiceAPI()
    cy.wait(1000)
    mainpage.WirelessPricing()
    cy.wait(1000)
    mainpage.AboutUs()
    cy.wait(1000)
    mainpage.Careers()
    cy.wait(1000)
    mainpage.AcceptableUsePolicy()
})
When("User clicks on side panel and click on links", () => {
    mainpage.SideBarButton()
    mainpage.Solutions()
    cy.get('.sc-6ef4e600-19').should('be.visible')
    mainpage.BackButton()
    mainpage.Resources()
    cy.get('.sc-6ef4e600-19').should('be.visible')
    mainpage.BackButton()
    mainpage.Company()
    cy.get('.sc-6ef4e600-19').should('be.visible')
    mainpage.BackButton()
    mainpage.Pricing()
    cy.get('.sc-6ef4e600-19').should('be.visible')
    mainpage.BackButton()
    mainpage.Network()
    })

Then("All links works correctly and user is located on last clicked link", () =>{
    cy.intercept("https://telnyx.com/acceptable-use-policy")
})
Then("All links works corretly and user is located on main page", () =>{
    cy.intercept("https://telnyx.com")
})
Then("All links works corretly and side panel is visible with all links", () =>{
    cy.intercept('https://telnyx.com/solutions/global-ip-network')
})
